name: cli_example
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.4.1

dev_dependencies:
  lints: ^2.1.1
  run_with_print: ^0.0.2
  test: ^1.21.0
